### ISSUE TITLE
lemonmon - Loss of unclaimed rewards if a bucket went bankrupt

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-ajna-judging#100]
lemonmon

high

# Loss of unclaimed rewards if a bucket went bankrupt

## Summary

When the `PositionManager.memorializePositions` function is called by a lender, they can potentially lose their unclaimed rewards in the case where a bucket went bankrupt.

## Vulnerability Detail

When a lender is calling the function `PositionManager.memorializePositions`, the protocol checks for previous deposits:

https://github.com/sherlock-audit/2023-04-ajna/blob/main/ajna-core/src/PositionManager.sol#L232

Then, if there are previous deposits, the protocol checks whether the bucket went bankrupt and zeros out the previous tracked LP:

https://github.com/sherlock-audit/2023-04-ajna/blob/main/ajna-core/src/PositionManager.sol#L234-L236

So when calling `PositionManager.memorializePositions`, the lender can potentially lose his unclaimed rewards, because claiming rewards relies on the tracked LP, which got zeroed out by `PositionManager.memorializePositions` (line 234-236) if the bucket went bankrupt.

The `RewardsManager.claimRewards`, which is used to claim the rewards, and it's subsequent called functions like `RewardsManager._calculateAndClaimAllRewards`, do not check whether the bucket is bankrupt:

https://github.com/sherlock-audit/2023-04-ajna/blob/main/ajna-core/src/RewardsManager.sol#L120-L144

https://github.com/sherlock-audit/2023-04-ajna/blob/main/ajna-core/src/RewardsManager.sol#L510-L546

## Impact

Lenders can lose unclaimed rewards.

## Code Snippet

https://github.com/sherlock-audit/2023-04-ajna/blob/main/ajna-core/src/PositionManager.sol#L232

https://github.com/sherlock-audit/2023-04-ajna/blob/main/ajna-core/src/PositionManager.sol#L234-L236

https://github.com/sherlock-audit/2023-04-ajna/blob/main/ajna-core/src/RewardsManager.sol#L120-L144

https://github.com/sherlock-audit/2023-04-ajna/blob/main/ajna-core/src/RewardsManager.sol#L510-L546

## Tool used

Manual Review

## Recommendation

Either:

Don't zero out the tracked LPs when a bucket went bankrupt inside the `PositionManager.memorializePositions` function (line 234-236).

Or:

Check whether a bucket went bankrupt when `RewardsManager.claimRewards` is called and don't pay any rewards in that case.

**Comment by 0xffff11** [comment]
I agree that the impact is somewhat severe and the fix seems that would not really be very difficult to implement, correct me if I am wrong. While I don't see the issue as a high, I could see the issue as a medium.

**Comment by mattcushman** [comment]
When a bucket goes bankrupt, it's because all of the lenders' deposits in that bucket has been rendered worthless (primarily caused by bad debt being pushed into the bucket). A lender should not expect to liquidity staking rewards on such a bucket -- for example, all of their previously earned interest goes away as well, and the rewards are proportional to interest earned within each epoch.

While they could have claimed these rewards before the bankruptcy (in some cases), they also could have withdrawn some or all of their deposit as well or used it to buy collateral in the auction.

For these reasons, it's reasonable to consider this a simple design decision for the rewards system/manager, which is used to offer discretionary enhanced incentives to initial liquidity providers.

**Comment by klauswaiss** [comment]
It is important to consider that eradicating earned rewards could disincentivize liquidity providers, since such a practice places a big risk on them. This could potentially lower their participation level.

Furthermore, LPs can't always predict bankruptcy of buckets and act accordingly by claiming rewards in time.

Also, in traditional finance, depositors don't lose their earned interest when a bank becomes insolvent, as it's considered their property. Which is why it's fair to say that LPs' earned rewards should be considered their property and protected accordingly. This is probably also what most LPs would expect from the protocol.

One can also say that rewards accrued become a form of vested interest, therefore these rewards should not be eradicated retroactively.

**Comment by lemonmon1984** [comment]
It is important to consider that eradicating earned rewards could disincentivize liquidity providers, since such a practice places a big risk on them. This could potentially lower their participation level.

Furthermore, LPs can't always predict bankruptcy of buckets and act accordingly by claiming rewards in time.

Also, in traditional finance, depositors don't lose their earned interest when a bank becomes insolvent, as it's considered their property. Which is why it's fair to say that LPs' earned rewards should be considered their property and protected accordingly. This is probably also what most LPs would expect from the protocol.

One can also say that rewards accrued become a form of vested interest, therefore these rewards should not be eradicated retroactively.

**Comment by dmitriia** [comment]
It looks to be a design limitation, i.e. developing more precise accounting was deemed not worth the increased complexity, size and usage costs.

Judging wise it is invalid as was [reported and discussed](https://github.com/code-423n4/2023-05-ajna-findings/issues/329) in the previous audit, whose results were public during the contest.

**Comment by mattcushman** [comment]
Ultimately, we acknowledge that one can make the argument that rewards earned for bankrupt positions that were earned in epochs prior to the bankruptcy should be retained.  One can also make the argument that they should not, as the interest that they had earned is lost.  As the Watson brings up tradfi, if a bank is insolvent the interest earned is preserved only to the extent that the bank's deposits are recovered/insured.  In this case, the pool is designed to work in isolation, without such a backstop.  Also, as dmitrii points out, this has been discussed before in the prior audit.  We decided to keep this behavior in the interest of simplicity.

**Comment by lemonmon1984** [comment]
In the previous C4 audit, this bug report was awarded as a valid high, https://github.com/code-423n4/2023-05-ajna-findings/issues/329.

In the current [Ajna Sherlock contest](https://audits.sherlock.xyz/contests/75) there is no mentioning, that this issue is a known issue, which is why I still consider this as a valid report.

**Comment by hrishibhat** [comment]
Result:
Low
Has duplicates
Considering this issue a valid low based on a couple of points raised above about the design decision:
> When a bucket goes bankrupt, it's because all of the lenders' deposits in that bucket has been rendered worthless (primarily caused by bad debt being pushed into the bucket). A lender should not expect to liquidity staking rewards on such a bucket -- for example, all of their previously earned interest goes away as well, and the rewards are proportional to interest earned within each epoch.
Also, the points raised here:
https://github.com/sherlock-audit/2023-04-ajna-judging/issues/100#issuecomment-1625910124

Also, an important point raised above is the previous audit report being public during the contest. Although the report was not added during the start of the contest, it was added during the contest period and was accessible via readme.
It is known that the above-mentioned report would also have been accessible to a significant of the Watsons prior to it being public. 
I agree that this may not be an ideal situation and may not have the best outcome for everyone, we are considering not accepting issues from the previous reports that are public at any point during the contest period.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ctf-sec](https://github.com/sherlock-audit/2023-04-ajna-judging/issues/100/#issuecomment-1620179619): rejected
