### ISSUE TITLE
MohammedRizwan - NFTs can be permanently locked or frozen if transferred to non-implemented onERC721Received support contract address(Missing issue in documentation too)

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-ajna-judging#17]
MohammedRizwan

high

# NFTs can be permanently locked or frozen if transferred to non-implemented onERC721Received support contract address(Missing issue in documentation too)

First of all before going deep in below report, I had a detail discussion with sponsors in discord private chat and the issue is confirmed with some agreed solution which is mentioned in recommendations and agreed for a fix by sponsors.

## Summary
NFTs can be permanently locked or frozen if transferred to non-implemented onERC721Received support contract address. Use ERC721.saferTransferFrom instead of ERC721.transferFrom when you send out NFT

## Impact

In ERC721Pool.sol contract, _transferNFT(..) function has used ERC721 transferFrom() to transfer the NFT to recepient. Which is shown as below,

```solidity
File: src/ERC721Pool.sol

622    function _transferNFT(address from_, address to_, uint256 tokenId_) internal {
623        // slither-disable-next-line calls-loop
624        IERC721Token(_getArgAddress(COLLATERAL_ADDRESS)).transferFrom(from_, to_, tokenId_);
625    }
```

_transferNFT() function is further used in _transferFromPoolToAddress() function which is given as below,

```solidity
File: src/ERC721Pool.sol

592    function _transferFromPoolToAddress(
593        address toAddress_,
594       uint256[] storage poolTokens_,
595        uint256 amountToRemove_
596    ) internal returns (uint256[] memory) {
597        uint256[] memory tokensTransferred = new uint256[](amountToRemove_);
598
599        uint256 noOfNFTsInPool = poolTokens_.length;
600
601        for (uint256 i = 0; i < amountToRemove_;) {
602            uint256 tokenId = poolTokens_[--noOfNFTsInPool]; // start with transferring the last token added in bucket
603            poolTokens_.pop();
604
605            _transferNFT(address(this), toAddress_, tokenId);
606
607            tokensTransferred[i] = tokenId;
608
609            unchecked { ++i; }
610        }
611
612        return tokensTransferred;
613    }
```

As seen above at L-624, transferFrom() method is used instead of safeTransferFrom(). I however argue that this isn’t recommended because:

The issue is if the recepient is a contract address, the NFT will be locked or frozen because of NO checkOnERC721Received support in current implementation.

Openzeppelin encourages to use safeTransferFrom instead of transferFrom and in ER721.sol, the comment says,

```solidity
File: contracts/token/ERC721/ERC721.sol

180     * @dev Safely transfers `tokenId` token from `from` to `to`, checking first that contract recipients
181     * are aware of the ERC721 protocol to prevent tokens from being forever locked.


193     * - If `to` refers to a smart contract, it must implement {IERC721Receiver-onERC721Received}, which is called upon a safe transfer.
```

OpenZeppelin’s documentation discourages the use of transferFrom(), Use safeTransferFrom() whenever possible,

Openzeppelin warns of using transfer( ) by saying,

"Note that the caller is responsible to confirm that the recipient is capable of receiving ERC721 or else they may be permanently lost. Usage of safeTransferFrom prevents loss, though the caller must understand this adds an external call which potentially creates a reentrancy vulnerability."

Also, As per the documentation of EIP-721:

```solidity

A wallet/broker/auction application MUST implement the wallet interface if it will accept safe transfers.
```
Reference: https://eips.ethereum.org/EIPS/eip-721

**Discussion with Sponsors(@dizzy):**
I had a detail discussion on safeTransferFrom() use instead of transferFrom() in _transferNFT() at L-624. I explained the impact of not using transferFrom() function which with current implementation will lock the user NFTs if it is transferred to contract address. It was also discussed the scenario after account abstraction will fully rollout where smart contracts will handle as account. While discussion, it was said the contracts will be used by some already deployed proxy contract. This proxy contract holds tokens. Inshort the contracts will used via. proxy contracts. Now the issue is the proxy contract does not implement the onERC721Received support which for sure wont be able to receive the NFTs and if the NFTs sent to contract address with NO onERC721Received support will lock or freeze the NFTs permanently. It also does not seems to be possible for redeployment of proxy contract to mitigate the issue. After all Pros and Cons, It was decided to go with current implementation only but these critical issues are NOT documented anywhere. These critical issue are not aware to users and integrators.

Discussion link for reference- https://discord.com/channels/@me/1119210314811056128/1119268553221214359

Please be noted Ajna 1st Sherlock contest had used safeTransferFrom() but later after discussion with integrators, It had to purposely use transferFrom() to allow integrators use their existing contracts / proxies.

Old contract link with safeTransferFrom() implementation- 
https://github.com/sherlock-audit/2023-01-ajna/blob/69732cef929414a95be9a722a2f1aafec7c2ab0f/contracts/src/ERC721Pool.sol#L633

## Code Snippet
https://github.com/ajna-finance/ajna-core/blob/e3632f6d0b196fb1bf1e59c05fb85daf357f2386/src/ERC721Pool.sol#L605

https://github.com/ajna-finance/ajna-core/blob/e3632f6d0b196fb1bf1e59c05fb85daf357f2386/src/ERC721Pool.sol#L624

For reference, see a closely similar Medium severity reported in a backed audit:
https://github.com/code-423n4/2022-04-backed-findings/issues/83

For reference, see a closely similar Medium severity reported in cally audit:
https://github.com/code-423n4/2022-05-cally-findings/issues/300

## Tool used
Manual Review

## Recommendation
1) It is recommended to use safeTransferFrom instead of transferFrom and Follow Checks-Effect-interaction pattern. But as per the detail discussion on this topic, this does not seems to be possible presently.
2) As discussed and agreed, Kindly mention these critical issues clearly in documentation for USERS as well as for INTEGRATORS to make sure their contracts support the NFT and they are not end up locked NFTs in their contracts.
3) Make a clear documents stating above issues pertaining to transfer of NFTs to contract addresses, also alert users the impact of transferring the NFT to contract address at Front-end user interface(UI).

**Comment by grandizzy** [comment]
to clarify: usage of plain transfer is a deliberate choice but since this issue was raised in several audits the reasons of doing such should be better document / explicitly stated in repo README / limitations

**Comment by mohammedrizwann123** [comment]
Escalate for 10USDC

This finding and #18 are both valid findings and its confirmed by sponsors(@grandizzy) and intend to fix it as per agreed recommendation(Point 2 and 3).

I had a detail discussion on these two issues (#17 and #18) with sponsors and highlighted sponsor discussion in reports. Sponsor(@grandizzy ) has also commented on both issues agreeing on recommendations. This report should not be seen from documents updation point of view or low or informatinal issue. Both of these issues are actually exists in contracts which sponsor also agrees but there is no mention of asset loss due to these critical issues for integrators and users. The user is non-technical and is not aware of these issues. 

Further to prove about the validity of this finding. These issues are not mentioned even in Readme.md as a known issues of these contracts. Integrators and users are at risk of loss of assets and the sponsor do agree with this risk but it was not mentioned in Readme.md.

> Q: Please list any known issues/acceptable risks that should not result in a valid finding.
N/A

Referring per sherlock rules, if both these issues are not made on paper or in report it may significantly damage the Ajna reputation as these issues are not documented.

>  Sherlock is exclusively focused on high and medium-severity findings, as these vulnerabilities will cause a loss of user funds and most materially damage the reputation of the protocols Sherlock seeks to protect.

This isssue is something different as it highlights both the technical recommendation as well as what sponsor is intend to incorporate due to integrator issue.

> there may be issues that are judged beyond the purview of this guide. 

Further on validity of this issue,

> Hierarchy of truth: Contest README > Sherlock rules for valid issues > Historical decisions. 
While considering the validity of an issue in case of any conflict the sources of truth are prioritized in the above order. 

> In case of conflict between information in the README vs Sherlock rules, the README overrides Sherlock rules.

Here the Readme.md should be consider Hierarchy of truth.

Lets also consider the another scenario which Ajna is facing with both of these issues. If the integrators intend to redeploy their contracts then both of these issues are resolved and makes the report important and in that case this report will be useful for Ajna to make the necessary changes in code before deployement.

Further the sponsor in #20 commented, "we should open https://github.com/sherlock-audit/2023-04-ajna-judging/issues/17 as documentation needs to be improved and could be an issue if for example one pulls collateral to a recipient that doesn't handle NFTs."  https://github.com/ajna-finance/ajna-core/blob/main/src/ERC721Pool.sol#L228

Request for a consideration of both issues as sponsor has confirmed and intend to fix as per recommendations.

Thank you.

**Comment by 0xffff11** [comment]
Same response as in issue: https://github.com/sherlock-audit/2023-04-ajna-judging/issues/18   Invalid. Not using safeTransfer instead of transfer , is the protocol is not damaged, it is a design decision. No impact is caused in the protocol. Anyone interacting with Ajna should build according. Thanks

**Comment by dmitriia** [comment]
Similarly, a [design choice](https://github.com/sherlock-audit/2023-04-ajna-judging/issues/18#issuecomment-1625327606).
#17 and #18 looks to be documentation improvements suggestions, valid lows.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue a valid low based on the above comments using transfer instead of safetransfer can be considered a design choice.

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [mohammedrizwann123](https://github.com/sherlock-audit/2023-04-ajna-judging/issues/17/#issuecomment-1621193939): rejected
