### ISSUE TITLE
PRAISE - in drawDebt() function, users inputted `amountToBorrow_` will always be reduced by the function  due to precision loss because _roundToScale() divides before multiplying

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-ajna-judging#5]
PRAISE

medium

# in drawDebt() function, users inputted `amountToBorrow_` will always be reduced by the function  due to precision loss because _roundToScale() divides before multiplying

## Summary
The problem is in the _roundToScale() function where division is done before multiplication.
```solidity
 function _roundToScale(
        uint256 amount_,
        uint256 tokenScale_
    ) pure returns (uint256 scaledAmount_) {
        scaledAmount_ = (amount_ / tokenScale_) * tokenScale_;
    }
```

## Vulnerability Detail
in the drawDebt() function there is a check to  ensure the borrower is not charged for additional debt that they did not receive, by making an external call to _roundToScale() function to calculate the `amountToBorrow_` with `poolState.quoteTokenScale`
```solidity
 // ensure the borrower is not charged for additional debt that they did not receive
        amountToBorrow_     = _roundToScale(amountToBorrow_, poolState.quoteTokenScale);//@audit-info _roundToScale() divs before mul
```

BUT, the _roundToScale()  function when performing the calculation, divides before multiplying which will cause precision loss.

This is a more vivid explanation: 

QUOTE_SCALE = 61,  So lets say `poolState.quoteTokenScale` is 61 and `amountToBorrow_` is 500.

This ` amountToBorrow_     = _roundToScale(amountToBorrow_, poolState.quoteTokenScale);`  will do  `(500 /61 )` which is `8.196721311475409` then multiply it by 61 = 500 according to this formular in normal maths ` scaledAmount_ = (amount_ / tokenScale_) * tokenScale_;`. so here `amountToBorrow_ `= 500

But, due to the fact that Solidity truncates the result of division we won't have `8.196721311475409` when _roundToScale()  does `(500 /61 )` , what we'll have is just `8` and when multiplying by 61 what we have is 488 instead 500.

## Impact
borrower is charged less than his debt in drawDebt() function due to precision loss because _roundToScale() divides before multiplying

## Code Snippet
https://github.com/sherlock-audit/2023-04-ajna/blob/main/ajna-core/src/ERC20Pool.sol#L140

https://github.com/sherlock-audit/2023-04-ajna/blob/main/ajna-core/src/libraries/helpers/PoolHelper.sol#L264
## Tool used

Manual Review

## Recommendation
Don't divide before multiplying in the  _roundToScale() function
And also look for another way to scale tokens with decimals <18

**Comment by Love4codes** [comment]
Escalate for 10 USDC

 users inputted amountToBorrow_ will always be reduced due precision loss.
 
 This is a more vivid explanation:

QUOTE_SCALE = 61, So lets say poolState.quoteTokenScale is 61 and amountToBorrow_ is 500.

This  `amountToBorrow_     = _roundToScale(amountToBorrow_, poolState.quoteTokenScale);` will do (500 /61 ) which is 8.196721311475409 then multiply it by 61 = 500 according to this formular in normal maths  `scaledAmount_ = (amount_ / tokenScale_) * tokenScale_;`. so here amountToBorrow_ = 500

But, due to the fact that Solidity truncates the result of division we won't have 8.196721311475409 when _roundToScale() does (500 /61 ) , what we'll have is just 8 and when multiplying by 61 what we have is 488 instead 500.

A significant loss of 12 $

**Comment by 0xffff11** [comment]
I would call this one a duplicate of https://github.com/sherlock-audit/2023-04-ajna-judging/issues/9 Same thing divide before multiplicate

**Comment by Love4codes** [comment]
> I would call this one a duplicate of #9 Same thing division before multiplication

Yes boss they're both division before multiplication but they happen on 2 different functions

**Comment by dmitriia** [comment]
Similarly to #9 this is user input correction that has to be done either way. It can be treated as a user mistake if extra decimals were entered in the first place.

**Comment by Love4codes** [comment]
> Similarly to #9 this is user input correction that has to be done either way. It can be treated as a user mistake if extra decimals were entered in the first place, i.e. division before multiplication is intentional, there is no issue here.

division before multiplication might be intentional but it will always reduce whatever value user gives as input here, which isn't proper fucntionality

**Comment by Love4codes** [comment]
> Similarly to #9 this is user input correction that has to be done either way. It can be treated as a user mistake if extra decimals were entered in the first place, i.e. division before multiplication is intentional, there is no issue here.

boss you have to look for a better way to scale tokens with < 18 decimals

**Comment by grandizzy** [comment]
> > Similarly to #9 this is user input correction that has to be done either way. It can be treated as a user mistake if extra decimals were entered in the first place, i.e. division before multiplication is intentional, there is no issue here.
> 
> @dmitriia Boss this isn't about user mistake.
> 
> division before multiplication might be intentional but it will always reduce whatever value user gives as input here, which isn't proper functionality
> 
> like in my given example of where a user inputs 500 as `amountToBorrow_`, the division before multiplication reduces the 500 to 488. which is a loss of 12 (500 - 488).
> 
> And this is worse when dealing with larger numbers.

That would be valid if `QUOTE_SCALE = 61` as in report but this is not possible. The `QUOTE_SCALE` is calculated in `_getTokenScale` function https://github.com/ajna-finance/ajna-core/blob/main/src/base/PoolDeployer.sol#L59 as
```Solidity
scale_ = 10 ** (18 - tokenDecimals_);
```
so it can only be a pow of 10, e.g. `1, 10**1, 10**2 ... 10**18`
Therefore a `500 /61` will never be possible, to give more clarity on how / why this method is used:
- pools accepts only WADs as input (e.g. when lender add quote token or when borrower draws debt they should specify amounts as WAD, regardless token precision)
- in a pool with USDC (precision 6) being quote token the scale will be calculated as `10 ** (18 - 6) = 10 ** 12`
- let's say one wants to borrow USDC and calls `drawDebt` function with a value of `1.111111111111111111 WAD` (`1111111111111111111`)
- since pool cannot send `1.111111111111111111` worth of USDC (due to precision) this amount is rounded down using `_roundToScale` as `1111111111111111111 / 10 ** 12` resulting in an amount of `1.111111` which can be handled by USDC token
- same is valid for lender adding quote tokens and other operations

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue a low based on the above comments.

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Love4codes](https://github.com/sherlock-audit/2023-04-ajna-judging/issues/5/#issuecomment-1616792545): rejected
